BEGIN

LET arr_databases ARRAY := ARRAY_CONSTRUCT('DB_AIRBNB_RAW', 'DB_AIRBNB_DEV', 'DB_AIRBNB_TEST', 'DB_AIRBNB', 'DB_AIRBNB_DEBUG');

FOR i IN 0 TO ARRAY_SIZE(:arr_databases) - 1 DO
    EXECUTE IMMEDIATE 'DROP DATABASE IF EXISTS ' || :arr_databases[i];
END FOR;

END;

DELETE FROM DB_AIRBNB_RAW.STAGING.BOOKINGS;
DELETE FROM DB_AIRBNB_RAW.STAGING.HOSTS;
DELETE FROM DB_AIRBNB_RAW.STAGING.LISTINGS;

DROP TABLE DB_AIRBNB_DEV.BRONZE.BRONZE_BOOKINGS;
DROP TABLE DB_AIRBNB_DEV.BRONZE.BRONZE_LISTINGS;
DROP TABLE DB_AIRBNB_DEV.BRONZE.BRONZE_HOSTS;

DROP TABLE DB_AIRBNB_DEV.SILVER.SILVER_BOOKINGS;
DROP TABLE DB_AIRBNB_DEV.SILVER.SILVER_LISTINGS;
DROP TABLE DB_AIRBNB_DEV.SILVER.SILVER_HOSTS;

DROP TABLE DB_AIRBNB_DEV.GOLD.DIM_HOSTS;
DROP TABLE DB_AIRBNB_DEV.GOLD.BOOKING_REVENUE;
DROP TABLE DB_AIRBNB_DEV.GOLD.DIM_BOOKINGS;
DROP TABLE DB_AIRBNB_DEV.GOLD.DIM_LISTINGS;
DROP TABLE DB_AIRBNB_DEV.GOLD.FACT_AIRBNB;
DROP TABLE DB_AIRBNB_DEV.GOLD.ONEBIGTABLE;

-- Delete duplicate rows if any exist in the staging.listings table based on booking_id and listing_id, keeping only the first occurrence based on filename ordering.

DELETE FROM db_airbnb_raw.staging.listings
WHERE (booking_id, listing_id) IN (
    SELECT booking_id, listing_id
    FROM (
        SELECT listing_id, booking_id, filename, ROW_NUMBER() OVER (PARTITION BY booking_id,  listing_id ORDER BY filename) AS rn
        FROM db_airbnb_raw.staging.bookings
    )
    WHERE rn = 2
);
