/* 
  Copy data from S3 bucket to corresponding staging tables.  
*/
COPY INTO HOSTS
  FROM @STG_AIRBNB_S3
  FILES=('hosts.csv')
  FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT_HEADER_METADATA')
  ON_ERROR=CONTINUE
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  INCLUDE_METADATA=(
    FILENAME = METADATA$FILENAME,
    FILE_ROW_NUMBER = METADATA$FILE_ROW_NUMBER,
    FILE_CONTENT_KEY = METADATA$FILE_CONTENT_KEY,
    FILE_LAST_MODIFIED = METADATA$FILE_LAST_MODIFIED,
    START_SCAN_TIME = METADATA$START_SCAN_TIME
  );

--select count(*) from DB_AIRBNB.STAGING.HOSTS;
--200

COPY INTO BOOKINGS
  FROM @STG_AIRBNB_S3
  FILES=('bookings.csv')
  FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT_HEADER_METADATA')
  ON_ERROR=CONTINUE
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  INCLUDE_METADATA=(
    FILENAME = METADATA$FILENAME,
    FILE_ROW_NUMBER = METADATA$FILE_ROW_NUMBER,
    FILE_CONTENT_KEY = METADATA$FILE_CONTENT_KEY,
    FILE_LAST_MODIFIED = METADATA$FILE_LAST_MODIFIED,
    START_SCAN_TIME = METADATA$START_SCAN_TIME
  );
--select count(*) from DB_AIRBNB.STAGING.BOOKINGS;
--5000

COPY INTO LISTINGS
  FROM @STG_AIRBNB_S3
  FILES=('listings.csv')
  FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT_HEADER_METADATA')
  ON_ERROR=CONTINUE
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  INCLUDE_METADATA=(
    FILENAME = METADATA$FILENAME,
    FILE_ROW_NUMBER = METADATA$FILE_ROW_NUMBER,
    FILE_CONTENT_KEY = METADATA$FILE_CONTENT_KEY,
    FILE_LAST_MODIFIED = METADATA$FILE_LAST_MODIFIED,
    START_SCAN_TIME = METADATA$START_SCAN_TIME
  );
--select count(*) from DB_AIRBNB.STAGING.LISTINGS;
--500