name: dbt Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  dbt-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install dbt-snowflake

      - run: dbt deps

      - run: dbt build